# Generated by Django 3.1.4 on 2020-12-02 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Executions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_execution', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('state', models.CharField(max_length=150, null=True)),
                ('country', models.CharField(max_length=150)),
                ('end_date', models.CharField(max_length=8, null=True)),
                ('start_date', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'executions_history',
            },
        ),
    ]
